name: biplazma
description: we bring people together

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  introduction_screen: ^1.0.8
  google_fonts: ^1.0.0
  lottie: ^0.3.3
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  google_sign_in: ^4.4.4
  flutter_svg: ^0.17.4
  font_awesome_flutter: ^8.8.1
  dotted_border: ^1.0.5
  mdi: ^2.0.0
  url_launcher: ^5.4.5
  toast: ^0.1.5
  double_back_to_close_app: ^1.2.0
  mask_text_input_formatter: ^1.0.6
  cached_network_image: ^2.2.0
  connectivity: ^0.4.8+2
  webview_flutter: ^0.3.21
  http: ^0.12.1
  flutter_typeahead: ^1.8.0
  circular_check_box: ^1.0.1
  flutter_launcher_icons: ^0.7.5
  loading_indicator: ^1.1.0
  auto_size_text: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0

flutter_icons:
  image_path_android: "assets/img/biplazma-1024.png"
  image_path_ios: "assets/img/biplazma-1024.png"
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/svg/
    - assets/json/
    - assets/json/anim/